//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_2_digital_vackarklocka {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Test {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Test() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2_2_digital_vackarklocka.Test", typeof(Test).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värdet är inte i intervallet 0-23..
        /// </summary>
        internal static string Error_Hour {
            get {
                return ResourceManager.GetString("Error_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värdet är inte i intervallet 0-59..
        /// </summary>
        internal static string Error_Minute {
            get {
                return ResourceManager.GetString("Error_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 1
        ///Test av standardkonstruktorn.
        ///
        ///{0}.
        /// </summary>
        internal static string Test1 {
            get {
                return ResourceManager.GetString("Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 2
        ///Test av konstruktorn med två parametrar, (9, 42).
        ///
        ///{0}.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 3
        ///Test av konstruktorn med tre parametrar, (13, 24, 7, 35).
        ///
        ///{0}.
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 4
        ///Ställer befintlig AlarmClock-object till 23:58 och låten den gå 13 minuter..
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 5
        ///Ställer befintligt AlarmClock-objekt till tiden 6:12 och alarmtiden till 6:15 och låter den gå 6 minuter..
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 6
        ///Testar egenskaperna så att undantag kastas då tid och alarmtid tilldelas felaktiga värden..
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test 7
        ///Testar konstruktorer så att undantag kastas då tid och alarmtid tilldelas felaktiga värden..
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
    }
}
